const saharLocations = [
  {
    location: "Adyar",
    name: "Hotel Topper",
    type: "Paid",
    time: ["3:00 AM", "4:00 AM"],
    description:
      "Near Adyar bus depot, Masjid Campus. Available entire Ramalan.",
  },
  {
    location: "Guindy",
    name: "Hotel Liberty",
    type: "Paid",
    time: ["3:30 AM", "4:30 AM"],
    address: "#64, Anna Salai, Near Guindy railway station",
    contact: ["044-22317400", "044-22330719"],
    description: "Available entire Ramalan.",
  },
  {
    location: "Guindy - Alandur",
    name: "Alandur Masjid (Masjid-E-Ahle Hadees)",
    type: "Free",
    time: ["3:00 AM", "4:30 AM"],
    description:
      "Near Aone stationary shop, Last 5 odd nights (21, 23, 25, 27, 29).",
  },
  {
    location: "Guindy Market",
    name: "AKR Trust (AKR Steel)",
    type: "Free",
    time: ["3:00 AM", "4:00 AM"],
    description: "Near Gandhi statue, available entire Ramalan.",
  },
  {
    location: "Guindy Market",
    name: "Gandhi Market Masjid",
    type: "Free",
    time: ["3:00 AM", "4:00 AM"],
    description: "Last 5 odd nights (21, 23, 25, 27, 29).",
  },
  {
    location: "Kodambakkam",
    name: "Private Arrangement",
    type: "Paid",
    price: "₹1000/month",
    contact: "Mohamed Meeran Sahib - 9176807107",
    description:
      "Near Kodambakkam Bridge & Hotel Udopi. Advance registration required.",
  },
  {
    location: "Nandanam",
    name: "FB Masjid",
    type: "Free",
    time: ["3:00 AM", "4:00 AM"],
    description:
      "Opp YMCA Ground. Register name during Asar. Available entire Ramalan.",
  },
  {
    location: "Pallikaranai",
    name: "Masjid-e-Noor",
    type: "Free",
    time: ["3:00 AM", "4:00 AM"],
    contact: "Mir Mumthaz Pasha - 9884229017",
    description: "Arrangements for night stay.",
  },
  {
    location: "Peryamet",
    name: "Hotel Fanar",
    type: "Paid",
    description:
      "Opp Peryamet Masjid. Expect other hotels to open at Sahar time.",
  },
  {
    location: "Saidapet",
    name: "Dasthgir Sahib Jama Masjid",
    type: "Free",
    time: ["3:00 AM", "4:00 AM"],
    contact: "Br. Sameeruddin - 9003231307",
    description: "Available entire Ramalan.",
  },
  {
    location: "Saidapet",
    name: "Nawab Shadullah Khan Masjid",
    type: "Free",
    time: ["3:10 AM onwards"],
    description:
      "Mosque Street, VGP Road area. Available entire Ramalan. No registration required.",
  },
  {
    location: "Sholinganallur",
    name: "Private Arrangement",
    type: "Paid",
    price: "₹2000/month",
    contact: "Aijaz - 9597458504",
    description:
      "Opp. Mohamed Sathak Arts & Science College. Advance registration required.",
  },
  {
    location: "Singaperumalkoil",
    name: "SP Koil Masjid",
    type: "Free",
    description:
      "5 mins walk from bus stop. Register during Taraweeh. Contact: Nawab Ali P.M - 9789970919.",
  },
  {
    location: "T.Nagar",
    name: "Hotel Virudhunagar",
    type: "Free",
    contact: "044-42122769",
    description: "77, G N Chetty Road, Panagal Park. Available entire Ramalan.",
  },
  {
    location: "Tambaram West",
    name: "Masjid Noor",
    type: "Free",
    time: ["3:00 AM", "4:00 AM"],
    description:
      "Near Perungalathur-Poonamallee Bypass. Available entire Ramalan.",
  },
  {
    location: "Taramani",
    name: "Masjid-e-Allah",
    type: "Free",
    time: ["3:00 AM", "4:00 AM"],
    description:
      "Near TCS, Vijayan Nagar, 100ft Road. Available entire Ramalan.",
  },
  {
    location: "Urappakkam",
    name: "Noor Hotel",
    type: "Free",
    contact: "Habeeb Rahuman - 9894190825",
    description: "Register and give tiffin carrier before Taraweeh.",
  },
  {
    location: "Velachery",
    name: "Thandeeswara Nagar Masjid",
    type: "Free",
    time: ["3:00 AM", "4:00 AM"],
    description: "Near IIT Gate (West). Available entire Ramalan.",
  },
  {
    location: "Velachery",
    name: "Masjidur Rahman",
    type: "Free",
    time: ["3:00 AM", "4:00 AM"],
    description: "Only for last 10 days.",
  },
  {
    location: "KK Nagar",
    name: "Banama Kitchen Hotel",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Available entire Ramalan.",
  },
  {
    location: "Triplicane",
    name: "Hotel Sagar",
    type: "Paid",
    time: ["3:00 AM - 4:00 AM"],
    description: "Available entire Ramalan.",
  },
  {
    location: "Choolaimedu",
    name: "Basha Street Masjid",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Only for last 10 days.",
  },
  {
    location: "Choolaimedu",
    name: "Azad Nagar Masjid",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Available entire Ramalan.",
  },
  {
    location: "Nungambakkam",
    name: "Jacob Kitchen",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Available entire Ramalan.",
  },
  {
    location: "Royapettah",
    name: "Hotel Barkath",
    type: "Paid",
    description: "Available entire Ramalan.",
  },
  {
    location: "Mount Road",
    name: "Hotel Buhari",
    type: "Paid",
    description: "Available entire Ramalan.",
  },
  {
    location: "Washermanpet",
    name: "Big Mosque",
    type: "Free",
    description: "Available entire Ramalan.",
  },
  {
    location: "Anna Nagar",
    name: "Masjid-e-Khadeejathul Kubra",
    type: "Free",
    description: "Available entire Ramalan.",
  },
  {
    location: "Perambur",
    name: "Masjid-e-Abubakar",
    type: "Free",
    description: "Available entire Ramalan.",
  },
  {
    location: "Egmore",
    name: "Hotel Crescent",
    type: "Paid",
    time: ["3:00 AM - 4:00 AM"],
    description: "Opposite Egmore Railway Station, available entire Ramalan.",
  },
  {
    location: "Purasaiwalkam",
    name: "Masjid-e-Mohideen",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Close to Abirami Mega Mall, last 10 nights.",
  },
  {
    location: "Vepery",
    name: "Rahmath Hotel",
    type: "Paid",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near Vepery High Road, entire Ramalan.",
  },
  {
    location: "Teynampet",
    name: "Al-Habeeb Restaurant",
    type: "Paid",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near SIET College, available entire Ramalan.",
  },
  {
    location: "Royapuram",
    name: "Big Mosque Royapuram",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Available entire Ramalan.",
  },
  {
    location: "Kottivakkam",
    name: "Masjid-e-Noor",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near ECR Road, only last 10 nights.",
  },
  {
    location: "Perungudi",
    name: "Masjid Al-Falah",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Close to Toll Plaza, entire Ramalan.",
  },
  {
    location: "Aminjikarai",
    name: "Masjid-e-Quba",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Behind Skywalk Mall, entire Ramalan.",
  },
  {
    location: "Arumbakkam",
    name: "Zam Zam Restaurant",
    type: "Paid",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near CMBT Bus Stand, available entire Ramalan.",
  },
  {
    location: "Vadapalani",
    name: "Masjid-e-Taqwa",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Opposite Vijaya Mall, entire Ramalan.",
  },
  {
    location: "Pallavaram",
    name: "Masjid-e-Bilal",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near Railway Station, last 10 nights.",
  },
  {
    location: "Chromepet",
    name: "Hotel Mubarak",
    type: "Paid",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near MIT Flyover, entire Ramalan.",
  },
  {
    location: "Koyambedu",
    name: "Masjid-e-Salam",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near Flower Market, entire Ramalan.",
  },
  {
    location: "Vyasarpadi",
    name: "Masjid-e-Sofia",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near MKB Nagar, last 10 nights.",
  },
  {
    location: "Manali",
    name: "Masjid-e-Rahmaniya",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near Manali New Town Bus Stop, entire Ramalan.",
  },
  {
    location: "Avadi",
    name: "Masjid-e-Madina",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near Avadi Market, entire Ramalan.",
  },
  {
    location: "Mogappair",
    name: "Masjid-e-Fathima",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near Golden Flats, last 10 nights.",
  },
  {
    location: "Tiruvottiyur",
    name: "Masjid-e-Siddique",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near Railway Station, entire Ramalan.",
  },
  {
    location: "Madhavaram",
    name: "Masjid-e-Nurul Islam",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near Madhavaram Roundtana, entire Ramalan.",
  },
  {
    location: "Shenoy Nagar",
    name: "Masjid-e-Hameedia",
    type: "Free",
    time: ["3:00 AM - 4:00 AM"],
    description: "Near Shenoy Nagar Metro Station, last 10 nights.",
  },
];

export default saharLocations;
