const saharLocations = [
  {
    location: "Pallavakkam",
    name: "5PM Café",
    type: "Paid",
    category: "Cafe",
    address: "Fifth Chennai in Pallavakkam (21, F Beach Road, MGR Salai)",
    time: "Time not available",
    contact: "-",
    description: "-",
  },
  {
    location: "Mylapore",
    name: "Aaga Mohideen Masjid",
    type: "Free",
    category: "Masjid",
    address: "Mosque St, Alamelu Manga Puram, Sankarapuram, Mylapore, Chennai – 600004",
    time: "Time not available",
    contact: "-",
    description: "Last 10 Days",
  },
  {
    location: "Poonamallee",
    name: "Abuthahir",
    type: "Free",
    category: "Home Delivery",
    address: "Poonamallee, Chennai",
    time: "2:30 AM onwards",
    contact: "Abuthahir Abuthahir – 9751092890",
    description: "Poonamallee | Open for All",
  },
  {
    location: "Guindy Market",
    name: "AKR Trust",
    type: "Free",
    category: "Organization",
    address: "Near Gandhi statue, Guindy Market, Chennai – 600032",
    time: "3:00–4:00 AM",
    contact: "-",
    description: "Entire Ramadan",
  },
  {
    location: "Teynampet",
    name: "Al Jabbar Sahar Meal",
    type: "Free",
    category: "Home Delivery",
    address: "41 Sarojini Street, Usman Road (Near Al Jabbar Restaurant), Chennai - 600017",
    time: "2:30 AM – 4:00 AM",
    contact: "9940321781",
    description: "Pre-registration must | Token issued February 14-16",
  },
  {
    location: "Triplicane",
    name: "Al Minar",
    type: "Free",
    category: "Masjid",
    address: "No.34, Triplicane High Rd, Ellis Puram, Padupakkam, Triplicane, Chennai – 600005",
    time: "Time not available",
    contact: "4448656116",
    description: "",
  },
  {
    location: "Kaladipet",
    name: "Al-Jamiatul Kamaliyah Sahar Meal",
    type: "Free",
    category: "Home Delivery",
    address: "No. 0/4 Poongavanapuram Main Road, Kaladipet, Chennai - 600019",
    time: "3:00 AM – 4:00 AM",
    contact: "9841195318",
    description: "Pre-registration must | For students/workers/hospital guests",
  },
  {
    location: "Perungudi",
    name: "Alfatah Dawa Center Sahar",
    type: "Free",
    category: "Home Delivery",
    address: "No. 2 Valmiki Street, Thiruvalluvar Nagar, Perungudi, Chennai - 600096",
    time: "11:00 PM – 12:00 AM",
    contact: "9551711510",
    description: "provided after taraweeh | Delivered to workplaces/hostels for paid for ladies",
  },
  {
    location: "Saidapet",
    name: "Althaf® Food Court",
    type: "Free",
    category: "Food Court",
    address: "9/5, Taluk Office Rd, Little Mount, Saidapet, Chennai 600015",
    time: "Time not available",
    contact: "7305814763",
    description: "",
  },
  {
    location: "Rangarajapuram",
    name: "Anju Light Mosque",
    type: "Free",
    category: "Masjid",
    address: "Near Rangarajapuram Bridge, Rangarajapuram, Chennai",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Pallavaram",
    name: "Ar Rahman Hotel",
    type: "Free",
    category: "Hotel/Restaurant",
    address: "No.135, Mosque Street, K. Pallavaram, Chennai - 600043 (Opposite Saiwa Kitchen)",
    time: "Time not available",
    contact: "-",
    description: "Parcel only. Pre-registration must, call to verify.",
  },
  {
    location: "Chromepet",
    name: "Ar-Rahman Islamic Taqwa Center Sahar",
    type: "Free",
    category: "Home Delivery",
    address: "57/58, Lakshmi Nagar, 2nd Cross Street, Heena Tower, Chromepet, Chennai - 600044",
    time: "11:00 PM – 11:30 PM",
    contact: "9941234386",
    description: "Pre-registration must | Free sahur parcel nightly",
  },
  {
    location: "Ambattur",
    name: "Avadi",
    type: "Free",
    category: "Home Delivery",
    address: "Sai Nagar Plot, 14, 3rd Main Rd, near Telephone Exchange, Old Ambattur, Mogappair West, Ambattur Industrial Estate, Chennai, Tamil Nadu 600058",
    time: "3:00 AM – 4:00 AM",
    contact: "8940753018",
    description: "Open for All",
  },
  {
    location: "Choolaimedu",
    name: "Azad Nagar Masjid",
    type: "Free",
    category: "Masjid",
    address: "Maraimalai St, Ayyavoo Colony, Choolaimedu, Chennai – 600030",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Choolaimedu",
    name: "Basha Street Masjid",
    type: "not updated",
    category: "Dine In",
    address: "Choolaimedu Main Road, Chennai - 600094",
    time: "3:00 AM – 4:00 AM",
    contact: "not updated – 1234567890",
    description: "Only for last 10 days",
  },
  {
    location: "Palavakkam",
    name: "BBB Nisha Trust",
    type: "Free",
    category: "Organization",
    address: "No 76, Near Corporation Bank, VGP Layout Part 1, 2nd Main Road, Palavakkam, Chennai – 600041",
    time: "Time not available",
    contact: "9445253385",
    description: "",
  },
  {
    location: "Washermanpet",
    name: "Big Mosque",
    type: "Free",
    category: "Masjid",
    address: "Washermanpet Main Road, Washermanpet, Chennai – 600021",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Royapuram",
    name: "Big Mosque Royapuram",
    type: "Free",
    category: "Masjid",
    address: "Royapuram Main Road, Royapuram, Chennai – 600013",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Perungudi",
    name: "Bilal - Kebabs & Biryani Perungudi",
    type: "Free",
    category: "Restaurant",
    address: "18, Ramappa Nagar Main Road, Perungudi, Chennai – 600096",
    time: "02:45 AM onwards",
    contact: "-",
    description: "Free Sahar available during Ramadan, Perungudi branch. Call ahead for details.",
  },
  {
    location: "ECR / Palavakkam",
    name: "Bilal at ECR Restaurant",
    type: "Free",
    category: "Restaurant",
    address: "1/174, East Coast Road (ECR), Palavakkam, Chennai – 600041",
    time: "02:45 AM onwards",
    contact: "-",
    description: "Free Sahar available during Ramadan at ECR branch. Call ahead for details.",
  },
  {
    location: "Teynampet",
    name: "Chennai Foodbank",
    type: "Free",
    category: "Organization",
    address: "Chennai Foodbank, Teynampet, Chennai – 600018",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Palavakkam",
    name: "Coronet Hotel",
    type: "Free",
    category: "Hotel",
    address: "Near Palavakkam Big Masjid, Palavakkam, Chennai – 600041",
    time: "Time not available",
    contact: "044-43861066",
    description: "Coupon Required",
  },
  {
    location: "Saidapet",
    name: "Dasthgir Sahib Jama Masjid",
    type: "Free",
    category: "Masjid",
    address: "Br. Sameeruddin Street, Saidapet, Chennai – 600015",
    time: "Time not available",
    contact: "Br. Sameeruddin – 9003231307",
    description: "Entire Ramadan",
  },
  {
    location: "Neelankarai",
    name: "Dubai Kitchen",
    type: "Free",
    category: "Restaurant",
    address: "4/131, SH 49, Saraswathi Nagar, Neelankarai, Chennai – 600115",
    time: "Time not available",
    contact: "9841595523",
    description: "",
  },
  {
    location: "Nandanam",
    name: "FB Masjid",
    type: "Free",
    category: "Masjid",
    address: "Opp. YMCA Ground, Nandanam, Chennai – 600035",
    time: "Time not available",
    contact: "-",
    description: "Register during Asar",
  },
  {
    location: "Triplicane",
    name: "Firdowz Triplicane",
    type: "Paid",
    category: "Restaurant",
    address: "No 307, Triplicane High Rd, SVM Nagar, Padupakkam, Triplicane, Chennai – 600005",
    time: "3:00 AM – 4:00 AM",
    contact: "4442157174",
    description: "Sahar available during entire Ramalan",
  },
  {
    location: "Saidapet West",
    name: "Gandhi Market Masjid",
    type: "Free",
    category: "Masjid",
    address: "Gandhi Market Area, Saidapet West, Chennai – 600015",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Sipcot Siruseri",
    name: "Hameed Fathima Jumma Masjid",
    type: "Paid",
    category: "Masjid",
    address: "Sipcot Siruseri, Chennai",
    time: "Parcel after Taraweeh",
    contact: "9786038530",
    description: "₹130 Per Day, Registration Mandatory",
  },
  {
    location: "Royapettah",
    name: "Hotel Barkath",
    type: "Paid",
    category: "Restaurant",
    address: "Royapettah, Chennai",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Mount Road",
    name: "Hotel Buhari",
    type: "Paid",
    category: "Restaurant",
    address: "Mount Road, Chennai",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Periamet",
    name: "Hotel Fanar",
    type: "Paid",
    category: "Hotel",
    address: "Opp Peryamet Masjid, Periamet, Chennai – 600081",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Guindy",
    name: "Hotel Liberty",
    type: "Paid",
    category: "Hotel",
    address: "#64, Anna Salai, Near Guindy Railway Station, Guindy, Chennai – 600032",
    time: "Time not available",
    contact: "044-22317400",
    description: "",
  },
  {
    location: "Chrompet",
    name: "Hotel Mubarak",
    type: "Paid",
    category: "Restaurant",
    address: "Chrompet, Chennai",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Ramapuram",
    name: "Hotel Nei Soru",
    type: "Free",
    category: "Hotel",
    address: "2/1, Ponnusamy St, Shanthi Nagar, Ramapuram, Chennai – 600089",
    time: "Time not available",
    contact: "9884215786",
    description: "",
  },
  {
    location: "Meenambakkam",
    name: "Hotel Southern Comfort",
    type: "Paid",
    category: "Hotel",
    address: "Old Station Road, 5, Grand Southern Trunk Rd, Meenambakkam, Chennai – 600016",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Adyar",
    name: "Hotel Topper",
    type: "Paid",
    category: "Hotel",
    address: "Near Adyar bus depot, Masjid Campus, Adyar, Chennai – 600020",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "T Nagar",
    name: "Hotel Virudhunagar Restaurant",
    type: "Not specified",
    category: "Hotel",
    address: "PANAGAL PARK, 77, Gopathy Narayana Rd, T. Nagar, Chennai, Tamil Nadu 600017",
    time: "2:30 AM onwards",
    contact: "-",
    description: "Pls contact Hotel Virudhunagar Restaurant, T Nagar branch to get sahar food. Asalamu Alaikum. Pre-registration must, call to verify.",
  },
  {
    location: "Area missing",
    name: "Irfan Bhai – Hotel",
    type: "Free",
    category: "Hotel",
    address: "Address missing",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Nungambakkam",
    name: "Jacob Kitchen",
    type: "Free",
    category: "Hotel",
    address: "Nungambakkam Main Road, Nungambakkam, Chennai – 600034",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Guduvanchery",
    name: "Jumma Masjid",
    type: "Free",
    category: "Masjid",
    address: "Opp. Guduvanchery Bus Stand, Guduvanchery, Chennai",
    time: "Time not available",
    contact: "9345760906",
    description: "Entire Ramadan",
  },
  {
    location: "Kodambakkam",
    name: "Kodambakkam Monthly Sahar",
    type: "Paid",
    category: "Masjid",
    address: "Opp. Sekar Emporium, Kodambakkam, Chennai",
    time: "Time not available",
    contact: "9176807107",
    description: "₹1000 Monthly",
  },
  {
    location: "Kolathur",
    name: "Kolathur Sahar Friends Group",
    type: "Free",
    category: "Home Delivery",
    address: "Samdaria Colony, Kolathur, Chennai - 600099",
    time: "3:00 AM – 4:00 AM",
    contact: "8428377778",
    description: "Pre-registration must | Sahur for workers/hospital visitors",
  },
  {
    location: "Medavakkam",
    name: "Madrasathul Haadi",
    type: "Free",
    category: "Masjid",
    address: "United Colony, Vengaivasal, Medavakkam, Chennai – 600100",
    time: "Time not available",
    contact: "8608602737",
    description: "",
  },
  {
    location: "Mandaiveli",
    name: "Mandaiveli Eidcah Masjid",
    type: "not updated",
    category: "Free",
    address: "No:32, Mandaveli, street Marys Road, Jeth Nagar, Chennai-600028, Tamil Nadu",
    time: "3:00 AM onwards",
    contact: "not updated – 9840290766",
    description: "",
  },
  {
    location: "Mandaiveli",
    name: "Mandaiveli Eidgah Sahar",
    type: "Free",
    category: "Home Delivery",
    address: "No: 32, Mandaveli Street Marys Road, Jeth Nagar, Mandaiveli, Chennai - 600028",
    time: "3:00 AM – 4:00 AM",
    contact: "9840290766",
    description: "Pre-registration must | Sahur meal available",
  },
  {
    location: "Saidapet West",
    name: "Market Palli",
    type: "Free",
    category: "Masjid",
    address: "Pookkara Theru (Canara Bank St), Saidapet West, Chennai",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Guduvanchery",
    name: "Market Palli Guduvanchery",
    type: "not updated",
    category: "Free",
    address: "Opp. Guduvanchery Bus Stand",
    time: "3:00 AM onwards",
    contact: "not updated – 1234567890",
    description: "Entire month",
  },
  {
    location: "Choolaimedu",
    name: "Masjid",
    type: "Free",
    category: "Masjid",
    address: "Choolaimedu Main Road, Choolaimedu, Chennai – 600094",
    time: "Time not available",
    contact: "-",
    description: "Last 10 Days",
  },
  {
    location: "Kandanchavadi",
    name: "Masjid Akbar",
    type: "Free",
    category: "Masjid",
    address: "Near Kandanchavadi Bus Stop, Kandanchavadi, Chennai",
    time: "Time not available",
    contact: "9840135749",
    description: "",
  },
  {
    location: "Perungudi",
    name: "Masjid Al-Falah",
    type: "Free",
    category: "Masjid",
    address: "Close to Toll Plaza, Perungudi, Chennai – 600096",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Taramani",
    name: "Masjid Allah",
    type: "Free",
    category: "Masjid",
    address: "Near TCS, Vijayan Nagar, 100ft Road, Taramani, Chennai – 600113",
    time: "3:00 AM onwards",
    contact: "-",
    description: "Entire Ramadan",
  },
  {
    location: "Ekkatuthangal",
    name: "Masjid Ar Rahman",
    type: "Free",
    category: "Masjid (Dine-in)",
    address: "69, Poonamalle Rd, Gandhinagar, Achuthan Nagar, Achugam Nagar, Ekkatuthangal, Chennai, Tamil Nadu 600032",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Royapeetah EB Office",
    name: "Masjid e Hussainy",
    type: "Free",
    category: "Home Delivery",
    address: "Mirza Ehsan Ali Khan Street, Royapeetah EB Office, Chennai",
    time: "3:00 AM – 4:00 AM",
    contact: "Ali Waris – 8870065124",
    description: "",
  },
  {
    location: "Periyar Nagar",
    name: "Masjid Husaneiya",
    type: "Free",
    category: "Masjid",
    address: "Address missing",
    time: "Time not available",
    contact: "8637655612",
    description: "",
  },
  {
    location: "Avadi",
    name: "Masjid Mubarak",
    type: "Free",
    category: "Masjid",
    address: "Vivekananda Nagar, TNHB MIG V Block, Avadi, Chennai – 600054",
    time: "Time not available",
    contact: "9710243600",
    description: "",
  },
  {
    location: "Avadi",
    name: "Masjid Mubarak Sahar Meal",
    type: "Free",
    category: "Home Delivery",
    address: "Masjid Mubarak, 1 N.M. Road, Avadi Market, Chennai - 600054",
    time: "3:00 AM – 4:15 AM",
    contact: "Abdul Aziz – 9094560414",
    description: "Pre-registration must | Poor/travelers welcome",
  },
  {
    location: "Tambaram West",
    name: "Masjid Noor",
    type: "Free",
    category: "Masjid",
    address: "Near Perungalathur-Poonamallee Bypass, Tambaram West, Chennai – 600045",
    time: "Time not available",
    contact: "-",
    description: "Entire Ramadan",
  },
  {
    location: "Perambur",
    name: "Masjid-E-Abubakar",
    type: "Free",
    category: "Masjid",
    address: "Perambur Main Road, Perambur, Chennai – 600011",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Alandur",
    name: "Masjid-E-Ahle Hadees",
    type: "Free",
    category: "Masjid",
    address: "Near Aone stationary shop, Alandur, Chennai – 600016",
    time: "3:00–4:30 AM",
    contact: "-",
    description: "Last 5 Odd Nights",
  },
  {
    location: "Taramani",
    name: "Masjid-E-Allah Jumma Masjid",
    type: "Free",
    category: "Masjid",
    address: "14, Mosque Street, Mahatma Gandhi Nagar, Taramani",
    time: "3:00 AM onwards",
    contact: "-",
    description: "Entire Ramadan",
  },
  {
    location: "Tambaram/East Medavakkam",
    name: "Masjid-e-Anwari",
    type: "not updated",
    category: "Free",
    address: "Sembakkam, Chennai-600073, Tamil Nadu",
    time: "4:00 PM – 7:00 PM",
    contact: "not updated – 9884193210",
    description: "Pre-booking required",
  },
  {
    location: "Tambaram/East Medavakkam",
    name: "Masjid-e-Anwari Sahar",
    type: "Paid",
    category: "Home Delivery",
    address: "Masjid-e-Anwari, Sembakkam, Chennai - 600073",
    time: "3:00 AM",
    contact: "9884193210",
    description: "Pre-registration must | Full Ramadan Sahur package available",
  },
  {
    location: "Madipakkam",
    name: "Masjid-E-Hameem",
    type: "Free",
    category: "Masjid",
    address: "Madipakkam Koot Road, near ICICI Bank and Ganesh Mahal, Madipakkam, Chennai",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Aminjikarai",
    name: "Masjid-E-Jannath",
    type: "Free",
    category: "Masjid",
    address: "Azad Nagar 1st Street, Aminjikarai, Chennai – 600029",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Nesappakkam",
    name: "Masjid-E-Noor",
    type: "Free",
    category: "Masjid",
    address: "NSC Bose Road, Khanu Nagar, Nesappakkam, Chennai – 600078",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Pallikaranai",
    name: "Masjid-E-Noor",
    type: "Free",
    category: "Masjid",
    address: "Mir Mumthaz Pasha, Pallikaranai, Chennai – 600100",
    time: "Night stay available",
    contact: "9884229017",
    description: "",
  },
  {
    location: "Kottivakkam",
    name: "Masjid-e-Noor Kottivakkam",
    type: "Free",
    category: "Masjid",
    address: "Kottivakkam Main Road, Chennai",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Nesappakkam",
    name: "Masjid-E-Noor Nesappakkam",
    type: "Free",
    category: "Masjid",
    address: "Nesappakkam, West KK Nagar, Chennai",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Pallikaranai",
    name: "Masjid-e-Noor Pallikaranai",
    type: "Free",
    category: "Masjid",
    address: "Pallikaranai Main Road, Chennai",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Madhavaram",
    name: "Masjid-E-Nurul Islam",
    type: "Free",
    category: "Masjid",
    address: "Near Madhavaram Roundtana, Madhavaram, Chennai – 600060",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Manali",
    name: "Masjid-E-Rahmaniya",
    type: "Free",
    category: "Masjid",
    address: "Near Manali New Town Bus Stop, Manali, Chennai – 600068",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Medavakkam",
    name: "Masjid-E-Rahmaniya",
    type: "Free",
    category: "Masjid",
    address: "3/311, Ram Nagar 12th Main Rd, Medavakkam, Chennai – 600091",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Triplicane",
    name: "Masjid-e-Salam",
    type: "Free",
    category: "Masjid",
    address: "Salam Street, Triplicane, Chennai – 600005",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Tiruvottiyur",
    name: "Masjid-E-Siddique",
    type: "Free",
    category: "Masjid",
    address: "Near Railway Station, Tiruvottiyur, Chennai – 600019",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Vyasarpadi",
    name: "Masjid-E-Sofia",
    type: "Free",
    category: "Masjid",
    address: "Near MKB Nagar, Vyasarpadi, Chennai – 600039",
    time: "Time not available",
    contact: "-",
    description: "Last 10 Nights",
  },
  {
    location: "Saidapet",
    name: "Masjid-e-Taqwa",
    type: "Free",
    category: "Masjid",
    address: "Taqwa Street, Saidapet, Chennai – 600015",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Pudupattinam",
    name: "Masjidun Noor ECR Sahar",
    type: "Free",
    category: "Home Delivery",
    address: "Masjidun Noor Mosque, ECR, Hajiyar Nagar, Pudupattinam - 603102",
    time: "3:00 AM – 4:00 AM",
    contact: "9894239866",
    description: "Pre-registration must | Free Sahur meal",
  },
  {
    location: "Velachery",
    name: "Masjidur Rahman",
    type: "Free",
    category: "Masjid",
    address: "Velachery Main Road, Chennai – 600042",
    time: "3:00–4:00 AM",
    contact: "-",
    description: "Last 10 Days",
  },
  {
    location: "Area missing",
    name: "Md Juvaid Noor J – Hotel",
    type: "Free",
    category: "Hotel",
    address: "Address missing",
    time: "3:30 AM",
    contact: "-",
    description: "Free, Parcel",
  },
  {
    location: "Arumbakkam",
    name: "MMDA Masjid",
    type: "Free",
    category: "Masjid",
    address: "Near Post Office, Arumbakkam, Chennai",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Perungudi",
    name: "Mount Road / NCR / OMR – Perungudi",
    type: "Free",
    category: "Masjid",
    address: "Perungudi Area, Chennai",
    time: "Tokens: 2:45 AM / Distribution: 3:00 AM",
    contact: "9655608700",
    description: "Monthly Sahar Subscription – Masjid Al Vilaya, ₹3,600 (30 Days) / ₹2,700 (22 Days)",
  },
  {
    location: "Mount Road",
    name: "Mount Road Bilal - Anna Salai",
    type: "Free",
    category: "Restaurant",
    address: "100/3, Anna Salai, Mount Road, Triplicane, Chennai, Tamil Nadu 600002",
    time: "02:45 AM onwards",
    contact: "-",
    description: "Free Sahar available during Ramadan. Call ahead for details.",
  },
  {
    location: "Saidapet",
    name: "Nawab Shadullah Khan Masjid",
    type: "Free",
    category: "Masjid",
    address: "Pookkara Theru (Canara Bank St), Saidapet, Chennai",
    time: "From 3:10 AM",
    contact: "-",
    description: "",
  },
  {
    location: "Vepery",
    name: "Nazeer BC – Vepery",
    type: "Paid",
    category: "Masjid",
    address: "Vepery, Chennai",
    time: "Time not available",
    contact: "9994566620",
    description: "Paid – ₹120",
  },
  {
    location: "Area missing",
    name: "Niyaz Bhai",
    type: "Paid",
    category: "Hotel",
    address: "Address missing",
    time: "After 3 AM",
    contact: "-",
    description: "Paid – ₹120",
  },
  {
    location: "Urapakkam",
    name: "Noor Masjid",
    type: "Free",
    category: "Masjid",
    address: "F2, Sulochana Villa, Poonga Street, Jagadeesh Nagar, Urapakkam – 603210",
    time: "Time not available",
    contact: "9976298356",
    description: "Entire Ramadan",
  },
  {
    location: "Pallavaram",
    name: "Paramakudi Bismillah Hotel",
    type: "Free",
    category: "Hotel/Restaurant",
    address: "No.139, Mosque Street, K. Pallavaram, Chennai - 600043 (Opposite Aattuthotti)",
    time: "Before Isha Prayer",
    contact: "9884996686",
    description: "Please collect token before Isha prayer. Call for bookings.",
  },
  {
    location: "Old Pallavaram",
    name: "Quba Masjid",
    type: "Paid",
    category: "Masjid",
    address: "5A Kovalan Street, Dargah Road, Old Pallavaram, Chennai",
    time: "Time not available",
    contact: "8122987130",
    description: "",
  },
  {
    location: "Old Pallavaram",
    name: "Rahmaniya Masjid and Madrasa",
    type: "Paid",
    category: "Masjid (Dine-In)",
    address: "Kavitha Pannai, Old Pallavaram, Chennai - 117",
    time: "3:30 AM – 4:30 AM",
    contact: "Syed Abuthahir – 9092541617",
    description: "",
  },
  {
    location: "Ramapuram",
    name: "Ramapuram Sahur Parcel",
    type: "Free",
    category: "Home Delivery",
    address: "Venkateswara Nagar, 12th Street, Opposite Vinayagar Temple, Ramapuram, Chennai - 600089",
    time: "2:30 AM – 4:00 AM",
    contact: "9047217378",
    description: "Pre-registration must | Parcel only",
  },
  {
    location: "Triplicane",
    name: "Sagar Hotel",
    type: "Paid",
    category: "Hotel",
    address: "116/239, Bharathi Salai, Padupakkam, Triplicane, Chennai – 600005",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "Sahar available during entire Ramalan",
  },
  {
    location: "Area missing",
    name: "Sahar Food Package",
    type: "Paid",
    category: "Organization",
    address: "Entire Ramadan",
    time: "Time not available",
    contact: "9444978779",
    description: "₹2300 (30 Days)",
  },
  {
    location: "Triplicane",
    name: "Saleem Mess Triplicane",
    type: "Paid",
    category: "Restaurant",
    address: "2, OVM Street, Triplicane, Chennai – 600005",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "Sahar available during entire Ramalan",
  },
  {
    location: "Sholinganallur",
    name: "Sholinganallur Monthly Sahar",
    type: "Paid",
    category: "Masjid",
    address: "Sholinganallur Area, Chennai",
    time: "Time not available",
    contact: "9597458504",
    description: "₹2000 Monthly",
  },
  {
    location: "OMR (Perungudi to Siruseri)",
    name: "Suhoor Food Initiative for Ladies - OMR",
    type: "Free",
    category: "Home Delivery",
    address: "Delivery zones: Perungudi (Iswarya Hospital) to Siruseri SIPCOT, Chennai",
    time: "Time not available",
    contact: "9342391015",
    description: "Pre-registration required: https://forms.gle/R5jASkt73P5FHx5V7. Only for sisters staying in PG / alone.",
  },
  {
    location: "Madras Medical College",
    name: "Umar Hussain – Madras Medical College",
    type: "Free",
    category: "Masjid / Organization",
    address: "Madras Medical College Campus, Chennai",
    time: "3:30 AM",
    contact: "9182919517",
    description: "Free, Girls Only",
  },
  {
    location: "Triplicane",
    name: "Yasmeen Mess Triplicane",
    type: "Paid",
    category: "Restaurant",
    address: "28, PN Dharga Main Street, Lawyers Road, Triplicane, Chennai – 600005",
    time: "3:00 AM – 4:00 AM",
    contact: "-",
    description: "Sahar available during entire Ramalan",
  },
  {
    location: "Ramapuram",
    name: "Zaara – Masjid-e-Hameedia",
    type: "Paid",
    category: "Masjid",
    address: "Ramapuram, Chennai",
    time: "4:15 AM",
    contact: "-",
    description: "Free, Parcel, Booking Required",
  },
  {
    location: "Arumbakkam",
    name: "Zam Zam Restaurant",
    type: "Paid",
    category: "Restaurant",
    address: "Near CMBT Bus Stand, Arumbakkam, Chennai – 600106",
    time: "Time not available",
    contact: "-",
    description: "",
  },
  {
    location: "Area missing",
    name: "Zulfiqar Ali Ahmed",
    type: "Paid",
    category: "Hotel / Masjid",
    address: "Address missing",
    time: "3:30 AM",
    contact: "-",
    description: "Free & Paid, ₹60",
  },
  {
    location: "Anna Nagar",
    name: "Masjid-e-Khadeejathul Kubra",
    type: "Free",
    category: "Masjid",
    address: "Anna Nagar, Chennai",
    time: "Time not available",
    contact: "-",
    description: "Available entire Ramadan",
  },
  {
    location: "Shenoy Nagar",
    name: "Masjid-e-Hameedia",
    type: "Free",
    category: "Masjid",
    address: "Near Shenoy Nagar Metro Station, Chennai",
    time: "Time not available",
    contact: "-",
    description: "Last 10 nights",
  },
  {
    location: "Alandur",
    name: "Masjidh Takwa",
    type: "Free",
    category: "Masjid",
    address: "M.K.N Road, Chakrapani Rd, Ramapuram, Race View Colony, Alandur, Chennai, Tamil Nadu 600032",
    time: "Time not available",
    contact: "Rahman – 9790945606",
    description: "",
  },
  {
    location: "Thousand Lights",
    name: "Masjid-e-mahamoodi",
    type: "Free",
    category: "Masjid",
    address: "Aziz mulk 2nd street, Thousand Lights, Chennai",
    time: "Time not available",
    contact: "Shahazad – 7561826284",
    description: "",
  },
  {
    location: "Mountroad",
    name: "Hotel bilal",
    type: "Free",
    category: "Hotel",
    address: "Lic near by, Mountroad, Chennai",
    time: "Time not available",
    contact: "Dhivanasik – 9952490226",
    description: "",
  },
  {
    location: "Royapettah",
    name: "Jamia Masjid Bathri ஜாமியா மஸ்ஜித் பாத்ரி",
    type: "Free",
    category: "Masjid",
    address: "Suha mansion jani jhan khan road, Royapettah, Chennai",
    time: "Time not available",
    contact: "Mohamed azeem – 9384113148",
    description: "",
  },
  {
    location: "Mandaveli",
    name: "Masjid eidgah",
    type: "Free",
    category: "Masjid",
    address: "Vanniyambathi street mandaveli, Chennai",
    time: "3:00-4:00 AM",
    contact: "Sameer Ahmed – 08248968556",
    description: "",
  },
  {
    location: "Triplicane",
    name: "Haja maideen",
    type: "Free",
    category: "Organization",
    address: "Kalaivanar arangam opp, Triplicane, Chennai",
    time: "2:00-4:00 AM",
    contact: "Haja maideen – 7604911315",
    description: "",
  },
];

export default saharLocations;
